### ISSUE TITLE
USB device

### ISSUE THREAD

**Issue by nzorea** [MarvellEmbeddedProcessors/edk2#10]
only if DOK was connected on power up, system crashes when removing DOK from port.
after disconnecting DOK, received multiple error messages, and than system becomes unusable:
XhcBulkTransfer: error - Device Error, transfer - 100
UsbBotExecCommand: UsbBotSendCommand (Device Error)

**Comment by nzorea** [comment]
this issue is only for USB2, in USB3 it works fine.
do you have any updates?

**Comment by dabros-jan** [comment]
After rebasing on top of current edk2, first tests have optimistic results,
but this issue needs more testing. We will update you then.

2016-06-22 9:52 GMT+02:00 nzorea notifications@github.com:

**Comment by wojtas-marcin** [comment]
Hi Nitzan,

On top of current edk2, I plugged/unplugged usb2 and usb3 sticks many times. No problems occurred, filesystem after map -u was easily accesible. Tested on both ports.

**Comment by nzorea** [comment]
Ok thanks.
