### ISSUE TITLE
Fix transfer speed drop in network

### ISSUE THREAD

**Issue by wojtas-marcin** [MarvellEmbeddedProcessors/edk2#4]
After the data is downloaded to UEFI with network, its speed decreases significantly. No impact on data integrity. Possible root cause - bad refilling of BM.

**Comment by wojtas-marcin** [comment]
Fixed in https://github.com/MarvellEmbeddedProcessors/edk2/commit/e5233a3b4fc1944dcfaef4b9e52a88505b7ab5c3

Driver in the newest version works stable and adds no latency during operation.

**Comment by shjzhou** [comment]
networking transfer speed is still much slower than u-boot

**Comment by wojtas-marcin** [comment]
Hi Joe, can you please provide with ATF and edk2 and opp revisions? How long exactly does it take to tftp kernel image? Around release containing SATA support I measured it to be around 11s for 11MB image. Today indeed there was some problem, but nothing changed around network in between (only changes in ATF). We'll have to take a look.

**Comment by shjzhou** [comment]
Hi Marcin,

ATF is 16.04.02, edk2 is the latest code I download from Github today (last commit: Platforms/Marvell: Remove ICU dependencies from Armada70x0.dsc file).
It took 70s to load 12MB kernel image.

**Comment by wojtas-marcin** [comment]
Are you also aligned with https://github.com/MarvellEmbeddedProcessors/edk2/commits/sh-edk2-2016.04-devel?

**Comment by shjzhou** [comment]
yes

**Comment by wojtas-marcin** [comment]
Can you please build image with the newest ATF (https://github.com/MarvellEmbeddedProcessors/atf-marvell-prv/commits/atf-v1.2-devel) and let know? I don't have an access to board now, so I can't do it on my own. There are over 30 commits on top of 16.04.02 bump release.

**Comment by shjzhou** [comment]
Why it is related to ATF? I loaded the UEFI.fd to DRAM and run from DRAM, it has nothing to do with ATF.

**Comment by wojtas-marcin** [comment]
First of all, can you provide with procedure of running UEFI.fd from DRAM? (What boot addresses, etc.) - from u-boot or uefi?

I was pointing to ATF, because network code has not been changed since a long time and on baseline from May 7th, I'm sure I measured ~1MB/s on A0 board with tftp downloading linux Image to ramdisk/usb/initial version of sata. On RZ board after completing the driver and increasing tftp block size to fit 1500 MTU measured value jumped to ~480kB/s (~25s) - either way 70s sound like an enormous value. Anyway, we need to take a look.

**Comment by shjzhou** [comment]
The way to load and boot from DRAM:
Under u-boot prompt:
tftp 0x0 edk2/Build/Armada70x0/DEBUG_GCC48/FV/ARMADA7040_EFI.fd
go 0x0

**Comment by shjzhou** [comment]
I retest the history git commits. Didn't find any version with good network performance either on A0 or Z1 board.

From the latest commits to the below commit:

367189889edf45f80fd39cc11b7211fdc023e7c2 
Platforms/Marvell: Add support for Armada70x0 platform

**Comment by wojtas-marcin** [comment]
Thanks, so on each commit you need 70s to tftp Linux image? And It was running uefi.fd from u-boot with atf 2016.02, right? No burning to spi?

**Comment by haimboot** [comment]
When using the version below (ATF/EDK2/OPP) no performance issue is observed.
- ATF 16.05.0 (currently latest)
- MMC release of EDK2 
   EKD2  patch "MdeModulePkg: Implement changes necessary for XENON controller"
   OPP patch "Correct PCD definitions in platform .dsc files"

I will update the commit ID in Marvell Uni-GIT once they are merged into Marvell's tree.

Joe,can you please test it with these commits?

**Comment by wojtas-marcin** [comment]
With:
- ATF 16.05.0
- edk2 and opp built from r20160530 release

Tftp download to ramdisk/sata/usb takes ~15s in our lab. Of course sd/mmc performance is much lower on this baseline. With fixed multiblock write (not included in release) it should be same as other storages.

**Comment by shjzhou** [comment]
I did compare with ATF 16.04.04 and 16.05.0 on our DB, the performance improved from 70s to 25s.

**Comment by haimboot** [comment]
Great. thanks for the update
