### ISSUE TITLE
Unable to update image by fupdate

### ISSUE THREAD

**Issue by shjzhou** [MarvellEmbeddedProcessors/edk2#6]
FS0:> fupdate -f flash-image-atf-1.2-devel-16.04.2.bin
fupdate: Bad Image checksum. 0x4C537DAF != 0x66BD5A39fupdate: Wrong firmware Image

This image is a good image(from official release), I can upgrade it from u-boot by "bubt".

**Comment by wojtas-marcin** [comment]
Can you please send the file?

**Comment by shjzhou** [comment]
See attached.

**Comment by wojtas-marcin** [comment]
Fixed in commit:
https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commit/7610ffe178f794b3fcc561b8592f53a087bf04e2
