### ISSUE TITLE
not all SD are detected

### ISSUE THREAD

**Issue by nzorea** [MarvellEmbeddedProcessors/edk2#9]
SDHC Kingston 16GB (SD4) is not detected

**Comment by wojtas-marcin** [comment]
Hi Nitzan,

Can you give more card details (e.g. link to amazon with exact model)?

Please provide with 'map -u' output when card is plugged.

**Comment by nzorea** [comment]
Link for amazon: http://www.amazon.com/Kingston-Class-Memory-SD4-16GBET/dp/B0021L9BKQ?ie=UTF8&*Version*=1&*entries*=0
I try map -u its didn't help.

**Comment by dabros-jan** [comment]
Hi Nitzan,

It will be helpful, if you could provide us log from 'map -u'. I
understand, that you don't get FS entry with proper filesystem, but is
there any SD device installed at PCI(0,3) device (BLK entry)?

Thanks,
Jan

2016-06-09 13:28 GMT+02:00 nzorea notifications@github.com:

**Comment by nzorea** [comment]
UEFI Interactive Shell v2.1
EDK II
UEFI v2.60 (Marvell devel-16.05.0, 0x00000001)
Mapping table
      FS1: Alias(s):F0:;BLK1:
          VenMsg(06ED4DD0-FF78-11D3-BDC4-00A0C94053D1,0000000000000000)
      FS0: Alias(s):F1:;BLK0:
          PciRoot(0x0)/Pci(0x3,0x0)/SD(0x0)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell>
Shell>
Shell>
Shell> map -u
Mapping table
      FS1: Alias(s):F0:;BLK1:
          VenMsg(06ED4DD0-FF78-11D3-BDC4-00A0C94053D1,0000000000000000)
      FS0: Alias(s):F1:;BLK0:
          PciRoot(0x0)/Pci(0x3,0x0)/SD(0x0)
Shell>

**Comment by dabros-jan** [comment]
Thanks for log.

I see that you have FS, which looks like filesystem on SD device. Cannot
you manage files on FS0? Please provide log from following commands:
Shell> fs0:
FS0: ls
FS0: vol

Is your card FAT or EXT formatted?

Regards,
Jan

2016-06-09 14:29 GMT+02:00 nzorea notifications@github.com:

**Comment by nzorea** [comment]
sorry, I confused with other log that works fine. Heere is the log without SD detection: 
UEFI Interactive Shell v2.1
EDK II
UEFI v2.60 (Marvell devel-16.05.0, 0x00000001)
Mapping table
      FS0: Alias(s):F0:;BLK1:
          VenMsg(06ED4DD0-FF78-11D3-BDC4-00A0C94053D1,0000000000000000)
     BLK0: Alias(s):
          PciRoot(0x0)/Pci(0x3,0x0)/SD(0x0)
Press ESC in 5 seconds to skip startup.nsh or any other key to continue.
Shell>
Shell>
Shell>
Shell>
Shell>
Shell> map -u
Mapping table
      FS0: Alias(s):F0:;BLK1:
          VenMsg(06ED4DD0-FF78-11D3-BDC4-00A0C94053D1,0000000000000000)
     BLK0: Alias(s):
          PciRoot(0x0)/Pci(0x3,0x0)/SD(0x0)
Shell>

**Comment by dabros-jan** [comment]
OK, now I see.

Is this card FAT or EXT formatted? If it is EXT, could you switch fo FAT
and perform test?

Regards,
Jan

2016-06-09 14:45 GMT+02:00 nzorea notifications@github.com:

**Comment by nzorea** [comment]
Ok, it's works after format.
But the detection depends on FS?

**Comment by dabros-jan** [comment]
FAT is the only FS fully supported in UEFI.
Regarding EXT support - it is 'experimental', but you should be able to use
it read-only.

Regards,
Jan

2016-06-09 15:07 GMT+02:00 nzorea notifications@github.com:
